version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: sudo chmod +x gradlew | gradle build sonarqube
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud